documents:
  driver_license:
    prompt: |
      Please analyze the provided image of a Japanese driver's license (運転免許証).
      Extract the following fields and return the result in a single, minified JSON object.
      If a field is not present, use an empty string "" as its value.
    json_structure:
      name: "氏名"
      address: "住所"
      birth_date: "生年月日"
      issue_date: "交付日"
      expiry_date: "有効期限"
      card_number: "免許の番号"
  my_number_card:
    prompt: |
      Please analyze the provided image of a My Number Card (マイナンバーカード).
      Extract the following fields and return the result in a single, minified JSON object.
      If a field is not present, use an empty string "" as its value.
    json_structure:
      name: "氏名"
      address: "住所"
      birth_date: "生年月日"
      issue_date: "交付日"
      expiry_date: "有効期限"
      card_number: "マイナンバー"
      gender: "性別"
